//! Logical agents vs runtime instances (CAT-05, ID-01/02) and presence.

use serde::{Deserialize, Serialize};
use serde_json::{Value, json};
use somework_core::{Error, ErrorCode, contracts::ActorKind, ids};

use crate::{
    audit::AuditRecord,
    db::{DbResultExt, scol},
    domain::{Ctx, Domain},
    events::EventSpec,
};

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase", default)]
pub struct RegisterRuntime {
    /// Must equal the `runtimeInstanceId` claim of the caller's credential; generated by the sidecar per process.
    pub runtime_instance_id: Option<String>,
    pub meta: Option<Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RuntimeView {
    pub runtime_instance_id: String,
    pub agent_id: String,
    pub domain_id: String,
    pub started_at: String,
    pub last_seen_at: String,
    pub status: String,
    pub meta: Value,
}

fn view(r: &sqlx::sqlite::SqliteRow) -> RuntimeView {
    RuntimeView {
        runtime_instance_id: scol(r, "runtime_instance_id"),
        agent_id: scol(r, "agent_id"),
        domain_id: scol(r, "domain_id"),
        started_at: scol(r, "started_at"),
        last_seen_at: scol(r, "last_seen_at"),
        status: scol(r, "status"),
        meta: crate::db::jcol(r, "meta"),
    }
}

impl Domain {
    pub async fn register_runtime(&self, ctx: &Ctx, req: RegisterRuntime) -> Result<RuntimeView, Error> {
        self.run(ctx, "runtime.register", async {
            if ctx.actor.kind != ActorKind::Agent {
                return Err(Error::denied("only agents register runtime instances"));
            }
            let claimed = ctx.actor.runtime_instance_id.clone();
            let rt = match (req.runtime_instance_id.clone(), claimed) {
                (Some(a), Some(b)) if a != b => return Err(Error::new(ErrorCode::SenderMismatch, "runtimeInstanceId does not match the credential")),
                (Some(a), _) => a,
                (None, Some(b)) => b,
                (None, None) => ids::runtime_instance_id(),
            };
            let this = self.clone();
            let ctx = ctx.clone();
            self.write(move |tx| {
                Box::pin(async move {
                    let now = this.now_ts();
                    let existing = sqlx::query("SELECT * FROM runtime_instances WHERE runtime_instance_id = ?").bind(&rt).fetch_optional(&mut **tx).await.db()?;
                    if let Some(row) = existing {
                        if scol(&row, "agent_id") != ctx.actor.id {
                            return Err(Error::new(ErrorCode::Conflict, "runtimeInstanceId is already used by another agent"));
                        }
                        if scol(&row, "status") != "active" {
                            return Err(Error::new(ErrorCode::Conflict, "runtimeInstanceId belongs to an ended process; every process needs a fresh id"));
                        }
                        sqlx::query("UPDATE runtime_instances SET last_seen_at = ? WHERE runtime_instance_id = ?").bind(&now).bind(&rt).execute(&mut **tx).await.db()?;
                    } else {
                        let before: i64 = sqlx::query_scalar("SELECT COUNT(*) FROM runtime_instances WHERE agent_id = ?").bind(&ctx.actor.id).fetch_one(&mut **tx).await.db()?;
                        let agent_known: Option<i64> = sqlx::query_scalar("SELECT 1 FROM agents WHERE agent_id = ?").bind(&ctx.actor.id).fetch_optional(&mut **tx).await.db()?;
                        if agent_known.is_none() {
                            return Err(Error::not_found("agent (register its AgentCard first)"));
                        }
                        sqlx::query("INSERT INTO runtime_instances(runtime_instance_id, agent_id, domain_id, started_at, last_seen_at, status, meta) VALUES (?, ?, ?, ?, ?, 'active', ?)")
                            .bind(&rt)
                            .bind(&ctx.actor.id)
                            .bind(&this.cfg.domain_id)
                            .bind(&now)
                            .bind(&now)
                            .bind(req.meta.clone().unwrap_or_else(|| json!({})).to_string())
                            .execute(&mut **tx)
                            .await
                            .db()?;
                        if before > 0 {
                            this.metrics.agent_runtime_restarts.inc();
                        }
                        let payload = json!({"agentId": ctx.actor.id, "runtimeInstanceId": rt, "state": "online"});
                        let spec = EventSpec::new("presence.changed", payload.clone()).recipient(ctx.actor.principal_id.clone(), false);
                        this.emit(tx, &ctx, spec).await?;
                        this.audit(tx, &ctx, AuditRecord::new("runtime.register", Some(format!("runtime://{rt}")), "success")).await?;
                    }
                    let row = sqlx::query("SELECT * FROM runtime_instances WHERE runtime_instance_id = ?").bind(&rt).fetch_one(&mut **tx).await.db()?;
                    Ok(view(&row))
                })
            })
            .await
        })
        .await
    }

    pub async fn runtime_heartbeat(&self, ctx: &Ctx) -> Result<RuntimeView, Error> {
        let rt = ctx.actor.runtime_instance_id.clone().ok_or_else(|| Error::denied("credential carries no runtimeInstanceId"))?;
        let res = sqlx::query("UPDATE runtime_instances SET last_seen_at = ? WHERE runtime_instance_id = ? AND agent_id = ? AND status = 'active'")
            .bind(self.now_ts())
            .bind(&rt)
            .bind(&ctx.actor.id)
            .execute(self.db.writer())
            .await
            .db()?;
        if res.rows_affected() == 0 {
            return Err(Error::not_found("runtime instance"));
        }
        let row = sqlx::query("SELECT * FROM runtime_instances WHERE runtime_instance_id = ?").bind(&rt).fetch_one(self.db.pool()).await.db()?;
        Ok(view(&row))
    }

    /// Presence signals arriving over core NATS only refresh instances that are already registered.
    pub async fn touch_runtime(&self, agent_id: &str, runtime_instance_id: &str) -> Result<bool, Error> {
        let res = sqlx::query("UPDATE runtime_instances SET last_seen_at = ? WHERE runtime_instance_id = ? AND agent_id = ? AND status = 'active'")
            .bind(self.now_ts())
            .bind(runtime_instance_id)
            .bind(agent_id)
            .execute(self.db.writer())
            .await
            .db()?;
        Ok(res.rows_affected() > 0)
    }

    pub async fn end_runtime(&self, ctx: &Ctx) -> Result<(), Error> {
        let rt = ctx.actor.runtime_instance_id.clone().ok_or_else(|| Error::denied("credential carries no runtimeInstanceId"))?;
        sqlx::query("UPDATE runtime_instances SET status = 'ended', ended_at = ? WHERE runtime_instance_id = ? AND agent_id = ?")
            .bind(self.now_ts())
            .bind(&rt)
            .bind(&ctx.actor.id)
            .execute(self.db.writer())
            .await
            .db()?;
        Ok(())
    }

    pub async fn list_runtimes(&self, ctx: &Ctx, agent_id: Option<&str>) -> Result<Vec<RuntimeView>, Error> {
        self.enforce_read(ctx, crate::policy::AuthzRequest::new("ops.read")).await?;
        let rows = sqlx::query("SELECT * FROM runtime_instances WHERE (? IS NULL OR agent_id = ?) ORDER BY started_at DESC LIMIT 500")
            .bind(agent_id)
            .bind(agent_id)
            .fetch_all(self.db.pool())
            .await
            .db()?;
        Ok(rows.iter().map(view).collect())
    }
}
